model_path: "./models/stable-diffusion-xl-base-1.0"
controlnet_path: "./models/controlnet-canny-sdxl-1.0"
refiner_path: "./models/stable-diffusion-xl-refiner-1.0"
vae_path: "./models/sdxl-vae-fp16-fix"

size: 1024
canny_low: 100
canny_high: 200
steps: 40
guidance: 8.0
conditioning: 0.9
refiner_steps: 40
refiner_start: 0.8
negative_prompt: "pattern, mosaic, grid, texture, noise, dots, pixelated, glitch, artifacts, sky artifacts, lowres, blurry, cartoon, poorly drawn, dirty, ugly, watermark, text, logo, signature, frame, border, cropped, out of frame, duplicate, low quality, bad grass, bad windows, bad architecture, old, ruin, broken, cracks, reflection artifacts, bad lighting, overexposed, underexposed, cluttered, crowded, people, person, face, hands, camera, out of focus"

input: "scetch.png"
prompt: "ultra-realistic minimalistic modern house, white concrete, large glass walls, clean smooth surfaces, evening golden hour lighting, photorealistic rendering, sharp lines, open plan, panoramic windows, architectural visualization, 8k, lawn, realistic grass, octane render, soft natural shadows, exterior, no people, no watermark, no text, high detail, crisp, elegant, beautiful"
